services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: devops-cicd-app:1.0
    container_name: devops-cicd-app
    ports:
      - "8080:3000"
    restart: unless-stopped